Repository oscar-system/GAP.jl, pull requests merged in 2024-09, with the labels that each got.

#1030 add `GetJuliaScratchspace` to `JuliaInterface`
  pkg/JuliaInterface/gap/JuliaInterface.gd
  pkg/JuliaInterface/gap/JuliaInterface.gi
  pkg/JuliaInterface/tst/utils.tst
  src/utils.jl
Labels: kind: enhancement

#1034 fix access to Julia docstrings from the GAP session
  pkg/JuliaInterface/gap/helpstring.g
  pkg/JuliaInterface/gap/juliahelp.g
  pkg/JuliaInterface/tst/help.tst
Labels: kind: bug

#1041 Remove JuliaModule
  pkg/JuliaInterface/gap/JuliaInterface.gd
  pkg/JuliaInterface/gap/JuliaInterface.gi
  pkg/JuliaInterface/tst/utils.tst
Labels: breaking

#1029 rewrite `julia_to_gap`
  CHANGES.md
  docs/src/conversion.md
  docs/src/examples.md
  docs/src/other.md
  pkg/JuliaInterface/gap/JuliaInterface.gd
  pkg/JuliaInterface/gap/convert.gd
  pkg/JuliaInterface/gap/convert.gi
  pkg/JuliaInterface/gap/juliahelp.g
  pkg/JuliaInterface/tst/convert.tst
  pkg/JuliaInterface/tst/help.tst
  src/adapter.jl
  src/ccalls.jl
  src/constructors.jl
  src/gap_to_julia.jl
  src/julia_to_gap.jl
  src/macros.jl
  src/types.jl
  src/wrappers.jl
  test/adapter.jl
  test/basics.jl
  test/constructors.jl
  test/convenience.jl
  test/conversion.jl
  test/macros.jl
  test/packages.jl
Labels: kind: enhancement, topic: conversion, breaking

#1043 Support keyword arguments in `CallJuliaFunctionWithCatch`, and a few other improvements
  pkg/JuliaInterface/gap/JuliaInterface.gd
  pkg/JuliaInterface/gap/calls.gi
  pkg/JuliaInterface/tst/utils.tst
  src/packages.jl
  src/utils.jl
Labels: kind: enhancement
